version: "3"
# Defines the version of the Docker Compose file format

services:
  # Defines the services to be created

  test_runner:
    build: .
    # Builds the Docker image for the test runner from the current directory
    image: pytest_runner
    # Names the built image as 'pytest_runner'
    container_name: pytest_runner_works1
    # Sets a specific name for the running container
    environment:
      - ENV=prod
      # Sets an environment variable within the container
    volumes:
      - .:/tests_project/
      # Mounts the current directory to /tests_project/ in the container
    command: ["python", "-m", "pytest", "-s", "--alluredir=test_results/", "/tests_project/tests/"]
    # The command that runs pytest with Allure results generation

  allure:
    image: frankescobar/allure-docker-service
    # Uses the Allure Docker Service image to serve the Allure report
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "1"
      # Environment variables for Allure Docker Service configuration
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports
      # Mounts directories for results and reports to the Allure service
    ports:
      - "5050:5050"
      # Exposes port 5050 to access the Allure report web UI

